### ISSUE TITLE
dpath.util.merge with dpath.util.MERGE_REPLACE doesn't work as expected

### ISSUE THREAD

**Issue by rayrapetyan** [akesterson/dpath-python#49]
Case:

> > > import dpath.util
> > > dct_a = {"a": {"b": [1,2,3]}}
> > > dct_b = {"a": {"b": [1]}}
> > > dpath.util.merge(dct_a, dct_b, flags=dpath.util.MERGE_REPLACE)
> > > dct_a

Expected:
{'a': {'b': [1]}}

Actual:
{'a': {'b': [1, 2, 3]}}

**Comment by calebcase** [comment]
Appears to be fixed with PR #50 
Can you confirm?

**Comment by akesterson** [comment]
PR #50 closed and deferred for 2.0, this remains an issue in 1.0

**Comment by neuroid** [comment]
A related issue:

```python
>>> import dpath.util
>>> dct_a = {"a": {"b": [1]}}
>>> dct_b = {"a": {"b": [1,2,3]}}
>>> dpath.util.merge(dct_a, dct_b, flags=dpath.util.MERGE_REPLACE)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/env/local/lib/python2.7/site-packages/dpath/util.py", line 203, in merge
    _path=separator.join([_path, str(v)]), separator=separator)
  File "/env/local/lib/python2.7/site-packages/dpath/util.py", line 203, in merge
    _path=separator.join([_path, str(v)]), separator=separator)
  File "/env/local/lib/python2.7/site-packages/dpath/util.py", line 206, in merge
    _check_typesafe(dst, src, i, separator.join([_path, str(i)]))
  File "/env/local/lib/python2.7/site-packages/dpath/util.py", line 189, in _check_typesafe
    elif ( (flags & MERGE_TYPESAFE != MERGE_TYPESAFE) and (type(obj1[key]) != type(obj2[key]))):
IndexError: list index out of range
```

**Comment by akesterson** [comment]
Pull Request #102 should resolve this, RFC
