### ISSUE TITLE
Unicode strings in dict keys causes UnicodeEncodingError to raise

### ISSUE THREAD

**Issue by danielpops** [akesterson/dpath-python#72]
```
>>> import dpath.path
>>> d = { u"Key Contains Unicode \u00af\u00f5": "value does not" }
>>> list(dpath.path.paths(d))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/danielpops/venv/local/lib/python2.7/site-packages/dpath/path.py", line 93, in paths
    validate(newpath)
  File "/home/danielpops/venv/local/lib/python2.7/site-packages/dpath/path.py", line 53, in validate
    strkey = str(key)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 21-22: ordinal not in range(128)
```

**Comment by calebcase** [comment]
Works in 2.0 - can be accomplished using segments.fold or segments.walk.

**Comment by calebcase** [comment]
Fixed in 2.x and 2.x is now released. Please upgrade and let us know how it goes. Thanks for the report!
